import { AiProvider, AiReport, AiStatus, AiUsage, ReportType } from "../../types/api";
import { SoftButton } from "../../components/primitives/SoftButton";
import { SegmentedControl } from "../../components/primitives/SegmentedControl";
import { SignalBadge } from "../../components/primitives/SignalBadge";
import { ReportCard } from "../../components/visuals/ReportCard";

const reportTypes: { type: ReportType; label: string }[] = [
  { type: "career_report", label: "Step 2: Career Brief" },
  { type: "learning_roadmap", label: "Step 3: 4-Week Roadmap" },
  { type: "project_suggestions", label: "Step 4: Portfolio Project Plan" }
];

export function AiBriefStudio({
  provider,
  onProvider,
  confirmed,
  onConfirm,
  status,
  usage,
  reports,
  selected,
  loading,
  activeType,
  cooldownRemaining,
  error,
  onGenerate,
  onSelect
}: {
  provider: AiProvider;
  onProvider: (provider: AiProvider) => void;
  confirmed: boolean;
  onConfirm: () => void;
  status?: AiStatus;
  usage?: AiUsage;
  reports: AiReport[];
  selected: AiReport | null;
  loading: boolean;
  activeType?: ReportType | null;
  cooldownRemaining: number;
  error?: string | null;
  onGenerate: (type: ReportType) => void;
  onSelect: (report: AiReport) => void;
}) {
  const needsOpenRouterConfirm = provider === "openrouter" && !confirmed;
  const providerLabel = provider === "openrouter" ? "OpenRouter" : "Mock";
  return (
    <div className="rounded-[1.5rem] border border-[#242933] bg-[#0d1014] p-6">
      <div className="grid gap-5 xl:grid-cols-[1fr_320px]">
        <div>
          <div className="flex flex-wrap items-start justify-between gap-4">
            <div>
              <p className="text-xs uppercase tracking-[0.16em] text-slate-500">AI Brief Studio</p>
              <h2 className="mt-2 text-2xl font-semibold text-slate-100">Turn this fit analysis into a career plan</h2>
              <p className="mt-2 text-sm leading-6 text-slate-400">Provider: {provider === "openrouter" ? "OpenRouter selected, quota/credits will be used only when you click Generate" : "Mock selected, local and deterministic"}</p>
            </div>
            <SegmentedControl<AiProvider> value={provider} onChange={onProvider} options={[{ value: "mock", label: "Mock" }, { value: "openrouter", label: "OpenRouter" }]} />
          </div>
          {provider === "openrouter" && (
            <div className="mt-4 rounded-2xl border border-amber-300/24 bg-amber-400/10 p-4 text-sm text-amber-200">
              OpenRouter uses your API quota/credits. StackRadar will only call it when you click Generate.
              {!confirmed && <SoftButton className="ml-3" variant="quiet" onClick={onConfirm}>Confirm OpenRouter</SoftButton>}
              {cooldownRemaining > 0 && <span className="ml-3">Cooldown: {cooldownRemaining}s</span>}
            </div>
          )}
          <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
            {reportTypes.map((report) => (
              <SoftButton
                key={report.type}
                variant={activeType === report.type ? "selected" : provider === "openrouter" ? "unselected" : "quiet"}
                disabled={loading || needsOpenRouterConfirm || cooldownRemaining > 0}
                onClick={() => onGenerate(report.type)}
              >
                Generate {report.label} with {providerLabel}
              </SoftButton>
            ))}
          </div>
          {error && <p className="mt-4 text-sm text-rose-300">{error}</p>}
          <div className="mt-6 min-h-[260px] rounded-[1.25rem] border border-[#20242b] bg-[#07090b] p-5">
            {loading ? <p className="text-sm text-slate-400">Generating one manual brief...</p> : selected ? <ReportReader report={selected} /> : <p className="text-sm text-slate-400">Choose a report type to generate a manual AI brief.</p>}
          </div>
        </div>
        <div>
          <div className="rounded-[1.25rem] border border-[#20242b] bg-[#07090b] p-4">
              <p className="text-sm font-semibold text-slate-100">Provider safety</p>
              <div className="mt-3 grid gap-2 text-sm text-slate-400">
              <p>OpenRouter configured: {status?.openrouter_configured ? "yes" : "no"}</p>
              <p>Mock reports: {usage?.mock_reports_total ?? 0}</p>
              <p>OpenRouter reports: {usage?.openrouter_reports_total ?? 0}</p>
              <p>AI used: Yes, only after clicking generate.</p>
            </div>
          </div>
          <div className="mt-4 space-y-3">
            {reports.slice(0, 4).map((report) => <ReportCard key={report.id} report={report} onClick={onSelect} />)}
          </div>
        </div>
      </div>
    </div>
  );
}

function ReportReader({ report }: { report: AiReport }) {
  return (
    <div>
      <div className="mb-4 flex flex-wrap gap-2">
        <SignalBadge tone={report.provider === "openrouter" ? "warn" : "neutral"}>Generated by: {report.provider}</SignalBadge>
        <SignalBadge>AI used: Yes</SignalBadge>
        <SignalBadge>Source data: StackRadar analytics</SignalBadge>
        <SignalBadge tone={report.reused_from_cache ? "good" : "neutral"}>Cached: {report.reused_from_cache ? "Yes" : "No"}</SignalBadge>
      </div>
      <pre className="whitespace-pre-wrap text-sm leading-7 text-slate-300">{report.output_text}</pre>
    </div>
  );
}
