import { AiProvider, AiReport, AiStatus, AiUsage, ReportType } from "../../types/api";
import { SoftButton } from "../../components/primitives/SoftButton";
import { SegmentedControl } from "../../components/primitives/SegmentedControl";
import { SignalBadge } from "../../components/primitives/SignalBadge";
import { ReportCard } from "../../components/visuals/ReportCard";

const reportTypes: { type: ReportType; label: string }[] = [
  { type: "career_report", label: "Career Report" },
  { type: "learning_roadmap", label: "4-Week Roadmap" },
  { type: "project_suggestions", label: "Project Ideas" },
  { type: "role_fit", label: "Role Fit" },
  { type: "skill_gap_brief", label: "Skill Gap Brief" }
];

export function AiBriefStudio({
  provider,
  onProvider,
  confirmed,
  onConfirm,
  status,
  usage,
  reports,
  selected,
  loading,
  activeType,
  cooldownRemaining,
  error,
  onGenerate,
  onSelect
}: {
  provider: AiProvider;
  onProvider: (provider: AiProvider) => void;
  confirmed: boolean;
  onConfirm: () => void;
  status?: AiStatus;
  usage?: AiUsage;
  reports: AiReport[];
  selected: AiReport | null;
  loading: boolean;
  activeType?: ReportType | null;
  cooldownRemaining: number;
  error?: string | null;
  onGenerate: (type: ReportType) => void;
  onSelect: (report: AiReport) => void;
}) {
  const needsGeminiConfirm = provider === "gemini" && !confirmed;
  return (
    <div className="rounded-[1.8rem] border border-slate-200 bg-white/90 p-6 shadow-[0_28px_80px_rgba(15,23,42,0.08)]">
      <div className="grid gap-5 xl:grid-cols-[1fr_320px]">
        <div>
          <div className="flex flex-wrap items-start justify-between gap-4">
            <div>
              <p className="text-xs uppercase tracking-[0.16em] text-slate-400">AI Brief Studio</p>
              <h2 className="mt-2 text-2xl font-semibold text-slate-950">Manual reports grounded in this fit analysis</h2>
              <p className="mt-2 text-sm leading-6 text-slate-500">Provider: {provider === "gemini" ? "Gemini selected, quota will be used" : "Mock selected, local and free"}</p>
            </div>
            <SegmentedControl<AiProvider> value={provider} onChange={onProvider} options={[{ value: "mock", label: "Mock" }, { value: "gemini", label: "Gemini" }]} />
          </div>
          {provider === "gemini" && (
            <div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">
              Gemini uses your API quota. Generate one report now?
              {!confirmed && <SoftButton className="ml-3" variant="quiet" onClick={onConfirm}>Confirm Gemini</SoftButton>}
              {cooldownRemaining > 0 && <span className="ml-3">Cooldown: {cooldownRemaining}s</span>}
            </div>
          )}
          <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
            {reportTypes.map((report) => (
              <SoftButton
                key={report.type}
                variant={activeType === report.type ? "selected" : provider === "gemini" ? "unselected" : "quiet"}
                disabled={loading || needsGeminiConfirm || cooldownRemaining > 0}
                onClick={() => onGenerate(report.type)}
              >
                Generate {report.label} with {provider === "gemini" ? "Gemini" : "Mock"}
              </SoftButton>
            ))}
          </div>
          {error && <p className="mt-4 text-sm text-rose-600">{error}</p>}
          <div className="mt-6 min-h-[260px] rounded-[1.35rem] border border-slate-100 bg-slate-50/70 p-5">
            {loading ? <p className="text-sm text-slate-500">Generating one manual brief...</p> : selected ? <ReportReader report={selected} /> : <p className="text-sm text-slate-500">Choose a report type to generate a manual AI brief.</p>}
          </div>
        </div>
        <div>
          <div className="rounded-[1.35rem] border border-slate-200 bg-slate-50/70 p-4">
            <p className="text-sm font-semibold text-slate-950">Provider safety</p>
            <div className="mt-3 grid gap-2 text-sm text-slate-500">
              <p>Gemini configured: {status?.gemini_configured ? "yes" : "no"}</p>
              <p>Mock reports: {usage?.mock_reports_total ?? 0}</p>
              <p>Gemini reports: {usage?.gemini_reports_total ?? 0}</p>
              <p>AI used: Yes, only after clicking generate.</p>
            </div>
          </div>
          <div className="mt-4 space-y-3">
            {reports.slice(0, 4).map((report) => <ReportCard key={report.id} report={report} onClick={onSelect} />)}
          </div>
        </div>
      </div>
    </div>
  );
}

function ReportReader({ report }: { report: AiReport }) {
  return (
    <div>
      <div className="mb-4 flex flex-wrap gap-2">
        <SignalBadge tone={report.provider === "gemini" ? "warn" : "neutral"}>Generated by: {report.provider}</SignalBadge>
        <SignalBadge>AI used: Yes</SignalBadge>
        <SignalBadge>Source data: StackRadar analytics</SignalBadge>
        <SignalBadge tone={report.reused_from_cache ? "good" : "neutral"}>Cached: {report.reused_from_cache ? "Yes" : "No"}</SignalBadge>
      </div>
      <pre className="whitespace-pre-wrap text-sm leading-7 text-slate-700">{report.output_text}</pre>
    </div>
  );
}
