import { AiReport } from "../../types/api";
import { SignalBadge } from "../../components/primitives/SignalBadge";

export function ReportReader({ report }: { report: AiReport | null }) {
  return (
    <div className="min-h-[420px] rounded-[1.8rem] border border-slate-200 bg-white/92 p-7 shadow-[0_30px_90px_rgba(15,23,42,0.09)]">
      {!report ? (
        <p className="text-sm text-slate-500">Select a report to read it here.</p>
      ) : (
        <>
          <div className="flex flex-wrap gap-2">
            <SignalBadge tone={report.provider === "gemini" ? "warn" : "neutral"}>Generated by: {report.provider}</SignalBadge>
            <SignalBadge>AI used: Yes</SignalBadge>
            <SignalBadge>Source data: StackRadar analytics</SignalBadge>
            <SignalBadge tone={report.reused_from_cache ? "good" : "neutral"}>Cached: {report.reused_from_cache ? "Yes" : "No"}</SignalBadge>
          </div>
          <h2 className="mt-6 text-3xl font-semibold capitalize text-slate-950">{report.report_type.replace(/_/g, " ")}</h2>
          <p className="mt-2 text-sm text-slate-400">{report.target_role} / {new Date(report.created_at).toLocaleString()} / model {report.model ?? "local"}</p>
          <pre className="mt-6 whitespace-pre-wrap text-sm leading-7 text-slate-700">{report.output_text}</pre>
        </>
      )}
    </div>
  );
}
